### PR TITLE
[fix] fix minor ambiguities

### PR DESCRIPTION
**Pull request by MangoIV**
- the nixos foundation *has* already endorsed anduril as a sponsor
- we want the nixos foundation to *reconsider* their current stance

### CODE REVIEW

**Review by Janik-Haag — COMMENTED** [review]
I would not change anything beyond typos. Changing the meaning after people singed this document seems like a really bad idea.

**Comment by rgri** [comment]
Can you clarify what is meant by "has already endorsed Anduril"? I don't see the sponsorship listed on the NixCon website or nix.org. Not that I don't believe you or anything, I'm just trying to keep on top of this situation.

**Comment by MangoIV** [comment]
@Janik-Haag 
> I would not change anything beyond typos. Changing the meaning after people singed this document seems like a really bad idea.

I don't think this changes any meaning, it just clarifies things

@rgri 
> Can you clarify what is meant by "has already endorsed Anduril"? I don't see the sponsorship listed on the NixCon website or nix.org. Not that I don't believe you or anything, I'm just trying to keep on top of this situation.

https://discourse.nixos.org/t/nixos-foundation-board-meeting-minutes-2024-01-02-2024-02-03/39994

> The decision is approved after evaluating the code of conduct, notes, and bylaws of the organizing entity (SCALE)

**Comment by MangoIV** [comment]
image

**Comment by FedericoSchonborn** [comment]
> Can you clarify what is meant by "has already endorsed Anduril"? I don't see the sponsorship listed on the NixCon website or nixos.org. Not that I don't believe you or anything, I'm just trying to keep on top of this situation.

For some reason [SCALEx](https://www.socallinuxexpo.org/scale/21x/nixcon-us) doesn't list them while the [NixCon](https://2024-na.nixcon.org/#sponsors) page does, but it is there.

**Comment by Janik-Haag** [comment]
https://github.com/NixOS-Users-Against-MIC-Sponsorship/NixOS-Users-Against-MIC-Sponsorship.github.io/pull/57/files#diff-c0db2152100428b43f7fb0d2c694e36549bb7dba6436e01e4ef3c7fd8f5d93c8R17 definitely does change the meaning.

> I don't think this changes any meaning, it just clarifies things

doesn't really matter, it might change the meaning for others that singed it under the current terms and conditions.

**Comment by MangoIV** [comment]
I would be open to change that part. But if you think this in general doesn't make sense, let's leave this untrue and misleading information up ;)

**Comment by rgri** [comment]
As a relative bystander, this seems like a weird response. @MangoIV I think you have a good point, in that it doesn't change the (very explicit) statement signing represents: "Signing this open letter only means that:[...]", but does add valuable context.

I think @Janik-Haag also has a good point though, about it being dangerous to silently change an already-signed letter.

If you truly believe this is important information, I think it's the wrong move to close and bury this issue. Can't we find a middle ground, maybe an addendum, or a timestamp of some kind? 

This situation is very confusing to follow as is- it is hard to even find where Nix Con NA supports Anduril, and it would be nice if this letter was complete.

**Comment by MangoIV** [comment]
I'm open to requests for any changes but I won't argue on whether it is a good idea in general to provide this information in a correct manner, I don't have time for that.

**Comment by Janik-Haag** [comment]
Not my repo, so not my decision to take, I know that I signed the letter in the current state and it feels wrong to me if people change the meaning of the initial message even if it's just a little.

> I would be open to change that part. But if you think this in general doesn't make sense, let's leave this untrue and misleading information up ;)

What untrue/misleading information? 

> as well as previous decisions about endorsing this sponsor for the NixCon NA 2024.

the only endorsement I'm aware of is the sponsor logo on the webpage and I was told that nothing more is/was planned.

**Comment by Janik-Haag** [comment]
Also fwiw, the foundation acknowledge the existence of this letter and talked about it in the bi-weekly board meeting, which can be seen here: https://matrix.to/#/!CJXQiUGqNPcFonEdME:nixos.org/$zanjedAYxKjFnz2nz5VFO51sGTJlUh9X_20mr4RN94c?via=nixos.org&via=matrix.org&via=nixos.dev so I would try avoiding spending more time on this then necessary.

**Comment by AngryAnt** [comment]
> I'm open to requests for any changes but I won't argue on whether it is a good idea in general to provide this information in a correct manner, I don't have time for that.

It is a fairly simple consideration: What is the downside of leaving the text as-is (1) or editing it (2):
1. Potentially having the letter slightly factually incorrect, though not in any manner which makes it more dismiss-able by those who would disagree.
2. Reducing the meaning of a signature by rendering the signed document non-constant. I would think I am not alone in not wanting to provide a card-blanche signature for whatever someone might want to change a document to. Yes the edit is likely immaterial for most signatories, but there is a reason why the principle exists (and is replicated in contract law) - I trust there is no need to further spell that out. Aside from all that, bypassing this consideration easily opens up the letter for hand-wavy dismissal from detractors "that letter does not mean anything - it is a moving target - not even the same as when people signed it".

I understand the desire to want to make the edit and agree with the edit itself. However, given the above, in my opinion any edit would do more harm than good. That is why with contracts you just live with the little inaccuracies that creep in or you create an addendum which the involved parties sign again.

**I realize that this letter is not a contract, but if the signatures on it are not treated with the same weight as contract signatures, then they may as well be likes on a blog post.**

**Pull request closed without merging**
